# Generated by Django 5.2 on 2025-05-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='Correo_paciente',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='Correo_final',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Centros_estudios_trabajos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Ciclo_paciente',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Estado_civil_paciente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Feche_de_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Grado_paciente',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Historiamedica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.historiamedica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Informante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Instruccion_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Lugar_de_nacimiento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Lugar_residencia_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Ocupacion_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Procedencia_paciente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Religion_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Telefono_paciente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Telefonos_adicionales',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Tiempo_residencia_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='is_menor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Accion_dia_problema',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Aproximacion_diagnostica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Calma_dia_problema',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Cargo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Conclusion_diagnostica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Desarrollo_problema',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Dia_anterior_problema',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Evolucion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Factores_problema',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Filosofia_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Hablar_problema_alguien',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Motivo_consulta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Nombre_responsable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Personalidad_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Programa_tratamiento',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Sintesis_baterias',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Sintesis_facultades',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Suceso_dia_problema',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Telefono_final',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Tiempo_problema',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='Universidad',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
