# Generated by Django 5.2 on 2025-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_paciente_correo_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Cantidad_tiempo_residencia_paciente',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
