# Generated by Django 5.2 on 2025-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paciente_cantidad_tiempo_residencia_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiamedica',
            name='Actual_trabajo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Aislamiento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Alimentacion_infancia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Ambiciones_laborales',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Armonia_madurez',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Cambios_profesion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Caracter_infantil',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Comportamiento_recreo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Comportamiento_salon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Control_encopresis',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Control_enuresis',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Crecimiento_psicosocial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Crianza_padres',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Cuadro_familiar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Desarrollo_voluntad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Dificultades_academicas_primaria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Dificultades_academicas_secundaria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Dificultades_academicas_superior',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Distocico',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Divorcio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Dtor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Economia_paciente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Edad_caminar_paciente',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Edad_control_enco',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Edad_madre_nacimiento',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Eleccion_pareja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Enfermedades_accidentes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Enuresis_paciente',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Estatura_nacer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Estilo_vida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Eutocico',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Fiel_exigente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Gestacion_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Grado_autonomia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Grado_integracion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Habitos_intereses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Ingreso_escuela_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Integracion_compañeros',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Jerarquia_valores',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Juego_humano',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Juego_imaginario',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Juego_infantil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Juego_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Lenguaje_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Llorar_nacer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Matrimonio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Motricidad_fina',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Motricidad_gruesa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Movimiento_pinza',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Norma_familiar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Noviazgos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Opinion_matrimonio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Otros_padres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Particularidades_adolescencia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Particularidades_boda',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Parto_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Perimetro_cefalico',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Perimetro_toraxico',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Persistencia_esfuerzo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Peso_nacer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Postnatalidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Problemas_afectivos_adolescencia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Problemas_afectivos_niñez',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Problemas_afectivos_pubertad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Problemas_legales',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Profesion_oficio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Razon_aisla',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Razon_parto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Recreacion_paciente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Reflejos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Relacion_demas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Relaciones_interpersonales',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Relaciones_sexos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Relaciones_trabajo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Religion_paciente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='SMO',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Separacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Servivio_militar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Sexualidad_actividad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Sistesis_problemas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Social_conocidos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Social_extraños',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Social_familiares',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Social_hermanos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Social_padres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Solo_madre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Solo_padre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Termino_parto',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Tipo_atencion_parto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Vida_matrimonial',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historiamedica',
            name='Vivienda_paciente',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
