# Generated by Django 5.2 on 2025-06-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_historiamedica_actual_trabajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='resultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resultado'),
        ),
    ]
