# Generated by Django 5.2 on 2025-06-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_paciente_cita_paciente_cita_acompañantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_consulta',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='modalidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_consulta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
