# Generated by Django 5.2.2 on 2025-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='familiares',
            field=models.ManyToManyField(null=True, to='oswald_api.familiar'),
        ),
    ]
