# Generated by Django 5.2.2 on 2025-06-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='acompañantes',
            field=models.ManyToManyField(blank=True, related_name='acompañantes', to='oswald_api.pacientes', verbose_name='acompañantes'),
        ),
    ]
