# Generated by Django 5.2.3 on 2025-06-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0002_pacientes_pregunta_1_pacientes_pregunta_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='enlace_reunion',
            field=models.URLField(blank=True, help_text='Enlace de Google Meet para citas online', max_length=500, null=True),
        ),
    ]
