# Generated by Django 5.2.2 on 2025-06-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0002_alter_pacientes_familiares'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='pregunta_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='pregunta_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='pregunta_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='respuesta_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='respuesta_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='respuesta_3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
