# Generated by Django 5.2.3 on 2025-06-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0003_cita_enlace_reunion'),
        ('oswald_api', '0003_pacientes_pregunta_1_pacientes_pregunta_2_and_more'),
    ]

    operations = [
    ]
