# Generated by Django 5.2.2 on 2025-06-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0002_alter_cita_acompañantes'),
        ('oswald_api', '0002_pacientes_pregunta_1_pacientes_pregunta_2_and_more'),
        ('oswald_api', '0003_pacientes_pregunta_1_pacientes_pregunta_2_and_more'),
    ]

    operations = [
    ]
