# Generated by Django 5.2.3 on 2025-06-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0004_merge_20250629_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='enlace_reunion',
        ),
        migrations.AddField(
            model_name='cita',
            name='historiamedica_archivo',
            field=models.FileField(blank=True, help_text='Archivo .docx de historia médica', null=True, upload_to='historias_medicas/'),
        ),
    ]
