# Generated by Django 5.2.3 on 2025-06-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oswald_api', '0004_merge_20250629_2003'),
        ('oswald_api', '0005_remove_cita_enlace_reunion_and_more'),
    ]

    operations = [
    ]
